### ISSUE TITLE
Cannot import infinispan-core 9.4.11.Final

### ISSUE THREAD

**Issue by mingfer** [infinispan/infinispan-spring-boot#114] opened 2019-04-25 06:27 UTC
**Describe the bug**
When I imported the 2.1.5.Final version of infinispan-spring-boot, I found that Infinispan-core and Infinispan-commons did not upgrade to 9.4.11.Final, or 9.1.7.Final

**To Reproduce**
1. My maven pom.xml configuration is as follows:
```xml
  <properties>
    <version.infinispan.starter>2.1.5.Final</version.infinispan.starter>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.infinispan</groupId>
      <artifactId>infinispan-spring-boot-starter-embedded</artifactId>
      <version>${version.infinispan.starter}</version>
    </dependency>
  </dependencies>
```
2. Pulled out the jar package:
![image](https://user-images.githubusercontent.com/46556397/56713953-dbe3ad80-6765-11e9-8f3c-afef1a810d84.png)

**Expected behavior**
I want to be able to use Infinispan-core and Infinispan-commons of 9.4.11.Final.

**Comment by karesti** [comment] 2019-04-25 08:47
@mingfer Would you please post your pom?

**Comment by mingfer** [comment] 2019-04-25 08:57
https://github.com/mingfer/demo/blob/master/demo-postgresql/pom.xml

**Comment by karesti** [comment] 2019-04-25 09:10
You re using 2.0.2.RELEASE of Spring-Boot: https://github.com/mingfer/demo/blob/master/pom.xml#L14
This version brings 9.1.7.Final Infinispan, instead of the latest Infinispan version.

https://github.com/spring-projects/spring-boot/blob/2.0.x/spring-boot-project/spring-boot-dependencies/pom.xml#L80

You need to override the property to use the infinispan version you need.
I would also recommend to upgrade to 2.1.4.RELEASE version instead of using 2.0.2.RELEASE. There are a bunch of fixes you will benefit from doing so.

Closing this issue, since this is not a bug of the starter.

**Closed by karesti** 2019-04-25 09:10 UTC
Labels: bug
