### ISSUE TITLE
Issue with hardwired marshaller

### ISSUE THREAD

**Issue by juliojgd** [infinispan/infinispan-spring-boot#152] opened 2020-06-29 17:05 UTC
https://github.com/infinispan/infinispan-spring-boot/blob/785b74403dc4ba46257f34e62e7069a2d20953bd/infinispan-spring-boot-starter-remote/src/main/java/org/infinispan/spring/starter/remote/InfinispanRemoteAutoConfiguration.java#L118

Hello, the highlighted line is hardwiring `JavaSerializationMarshaller` regardless of the marshaller configured by a InfinispanRemoteConfigurer or any other form of property configuration. I haven't been able to change the marshaller after changing to a version with this addition. I think this should not be done, to allow users to set their preferred marshaller, or , at leats, check if none is set previously.

In addition, in this [line 113](https://github.com/infinispan/infinispan-spring-boot/blob/785b74403dc4ba46257f34e62e7069a2d20953bd/infinispan-spring-boot-starter-remote/src/main/java/org/infinispan/spring/starter/remote/InfinispanRemoteAutoConfiguration.java#L113) it is called `builder.build()`  but after thar the builder is again used and modified (lines 116, 117 and 118) and finally the `builder.build()` is again called in line 119. Do you consider this a proper use of the builder pattern?

These are relatively recent changes, introduced in a documentation related issue, that is also confusing for  me.

Any thoughts? I can help if you consider this need to be fixed.

Thanks in advance for reading this.

**Comment by karesti** [comment] 2020-06-30 14:55
@juliojgd which marshaller would you like to use? overriding the marshaller should be working. The idea for this change was to override the default infinispan marshaller that does not work with spring session objects right now. But using an additional configurer should override this. However might indeed be a bug. I'm releasing the starter soon with the upcoming 11.0.1.Final.
Could you please provide a reproducer?
Thanks

**Comment by juliojgd** [comment] 2020-06-30 15:00
@karesti The InfinispanRemoteConfigurer is applied before the referenced line. 

How a configurer could possibly change this hardwired Marshaller if this hardwiring is donde in the **last line** before building the RemoteCacheManager? And after the appying of any configurer and properties) And I saw that is not possible to change the marsahller in a already built 'RemoteCacheManager '

Am I missing something? In the code it seems fairly clear.

**Comment by karesti** [comment] 2020-06-30 15:05
@juliojgd again, this is probably a bug introduced to fix that the protostream marshaller does not work with spring session and spring data right now.  Which marshaller would you like to use? 
Maybe we should let users to configure always the marshaller instead of trying to avoid the configuration.

**Comment by juliojgd** [comment] 2020-06-30 15:10
If the documentation says that the marshaller can be freely chosen using a configuration property,  I think it should let the user chose the marshaller by means of that property, the problem is not for a specific marshallerI need to use.
In addition I think the builder is not used according to the builder pattern, making changes after building it.
If you want help with this I can issue a PR, please let me know.

**Comment by karesti** [comment] 2020-06-30 15:16
@juliojgd concerning the builder, infinispan adds white list classes and these classes were not accessible from the builder object without building it. because if these marshaller changes, to get those white list classes and add them to the builder object, I needed to call "build" before. It's not code I'm happy about, and not the way the builder should be using generally speaking, but this is the way I found at the time I fixed the problem of marshalling and spring objects in the stater

**Comment by karesti** [comment] 2020-06-30 15:18
the documentation and the change was unaliged. I just wanted to avoid users to set up a marshaller all the time and deal with the white list classes of spring :(((
I will log a jira and remove the change of the hardcoded marshaller

**Comment by karesti** [comment] 2020-06-30 15:33
https://issues.redhat.com/browse/ISPN-12069

**Comment by karesti** [comment] 2020-06-30 15:40
@juliojgd would you mind testing with this ? https://github.com/infinispan/infinispan-spring-boot/pull/153

**Comment by karesti** [comment] 2020-06-30 15:51
@juliojgd we are bringing some of the tutorials that were in the repo into https://github.com/infinispan/infinispan-simple-tutorials/pull/107 (going to get merged soon)

we are releasing 11.0.1.Final very soon so I think I will upgrade here and release the starter once this is done

**Comment by juliojgd** [comment] 2020-06-30 16:01
> @juliojgd would you mind testing with this ? #153

Sure, I'll get to you with the test results.

**Comment by karesti** [comment] 2020-06-30 16:08
in 11.0.1.Final we do have a new testing utility with infinispan remote out of the box and test containers.
happy to get feedback if you use it :)

**Comment by juliojgd** [comment] 2020-06-30 21:41
> > @juliojgd would you mind testing with this ? #153
> 
> Sure, I'll get to you with the test results.

With this change https://github.com/infinispan/infinispan-spring-boot/pull/153 I have been able to change the marshaller and add a regexp to the whitelist by means of a InfinispanRemoteConfigurer. Sounds good for me. Thanks for the quick fix 😄

**Closed** 2020-07-01 10:10 UTC

**Comment by karesti** [comment] 2020-07-01 10:52
@juliojgd we have just released 2.3.1.Final. just the time it lands to maven central
